# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        clubs_logos_storage:
            adapter: 'asyncaws'
            visibility: public
            options:
                client: 'scaleway_object_storage_client'
                bucket: '%env(STORAGE_BUCKET_MYARCHERYCLUB)%'
                prefix: 'clubs'
        licensees_storage:
            adapter: 'asyncaws'
            options:
                client: 'scaleway_object_storage_client'
                bucket: '%env(STORAGE_BUCKET_MYARCHERYCLUB)%'
                prefix: 'licensees'
        events_storage:
            adapter: 'asyncaws'
            options:
                client: 'scaleway_object_storage_client'
                bucket: '%env(STORAGE_BUCKET_MYARCHERYCLUB)%'
                prefix: 'events'

when@test:
    flysystem:
        storages:
            clubs_logos_storage:
                adapter: 'memory'
                public_url_generator: 'App\Tests\FakePublicUrlGenerator'
            licensees_storage:
                adapter: 'memory'
                public_url_generator: 'App\Tests\FakePublicUrlGenerator'
            events_storage:
                adapter: 'memory'
                public_url_generator: 'App\Tests\FakePublicUrlGenerator'