framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'contact@monclubdetiralarc.fr'
        headers:
            From: "Mon Club de Tir à l'Arc <contact@monclubdetiralarc.fr>"
