vich_uploader:
    db_driver: orm
    storage: flysystem

    metadata:
        type: attribute

    mappings:
        clubs_logos:
            upload_destination: clubs_logos_storage
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'generateLogoName' }
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        licensees:
            upload_destination: licensees_storage
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'generateFilename' }
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        events:
            upload_destination: events_storage
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'generateFilename' }
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
