services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - APP_ENV=test
      - SONAR_TOKEN
      - CI
      - GITHUB_REF
      - GITHUB_BASE_REF
      - GITHUB_HEAD_REF
    command: sut

  database:
    image: mariadb:${MARIADB_VERSION:-10.8.2}
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: app_test
      MARIADB_PASSWORD: ChangeMe
      MARIADB_USER: symfony