services:
  app:
    volumes:
      - .:/app
      - app-var:/app/var
    ports:
      - "8080:80"

  messenger-async:
    volumes:
      - .:/app
      - app-var:/app/var

  scheduler-ffta-licensees:
    volumes:
      - .:/app
      - app-var:/app/var

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "13306:3306"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
###< symfony/mailer ###

volumes:
  app-var: