# Optional API Platform 4.1 enhancements
# Add these to your main api_platform.yaml if desired

api_platform:
    # Enhanced Swagger UI settings (4.1 syntax)
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
        # New in 4.1: Persist authorization across page refreshes
        persist_authorization: true
    
    # Enhanced OpenAPI settings
    openapi:
        # Better error documentation
        overrideResponses: false
