api_platform:
    title: Archery Manager
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure:
        include_type: true
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Dto'
#    resource_class_directories:
#        - '%kernel.project_dir%/src/Entity'
#        - '%kernel.project_dir%/src/Type'
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
        # New in 4.1: Persist authorization across page refreshes
        persist_authorization: true
    
    # Enhanced OpenAPI settings
    openapi:
        # Better error documentation
        overrideResponses: false