/*
 * Welcome to your app's main JavaScript file!
 *
 * We recommend including the built version of this JavaScript file
 * (and its CSS file) in your base layout (base.html.twig).
 */

import "./observability"

// any CSS you import will output into a single css file (app.css in this case)
import "./styles/app.scss";

// start the Stimulus application
import "./bootstrap";

// Bootstrap Javascript
import * as bootstrap from "bootstrap";

import {dom, library} from "@fortawesome/fontawesome-svg-core";
import {
  faAddressCard,
  faAngleLeft,
  faAngleRight,
  faArrowLeft,
  faArrowRight,
  faArrowRightFromBracket,
  faArrowsAlt,
  faArrowsRotate,
  faArrowUpRightFromSquare,
  faBan,
  faBell,
  faBolt,
  faBowArrow,
  faBox,
  faBoxes,
  faBuilding,
  faBullhorn,
  faBullseye,
  faCalendar,
  faCalendarCheck,
  faCalendarDays,
  faCalendarPlus,
  faCalendarWeek,
  faCalendarXmark,
  faChartBar,
  faChartLine,
  faCheck,
  faCheckCircle,
  faChevronLeft,
  faChevronRight,
  faCircleArrowRight,
  faCircleInfo,
  faCircleRight,
  faClock,
  faClipboardCheck,
  faClipboardList,
  faClockRotateLeft,
  faCog,
  faCogs,
  faComment,
  faCrosshairs,
  faDoorClosed,
  faDoorOpen,
  faDownload,
  faDumbbell,
  faEdit,
  faEllipsis,
  faEllipsisVertical,
  faEnvelope,
  faExclamationTriangle,
  faExternalLinkAlt,
  faEye,
  faFileContract,
  faFloppyDisk,
  faGaugeHigh,
  faGenderless,
  faHandHolding,
  faHeart,
  faHistory,
  faHome,
  faHourglass,
  faHourglassHalf,
  faIdBadge,
  faIdCard,
  faInfo,
  faInfoCircle,
  faInbox,
  faKey,
  faLightbulb,
  faList,
  faListCheck,
  faLock,
  faMap,
  faMapMarkerAlt,
  faMars,
  faMinus,
  faNoteSticky,
  faPaperclip,
  faPaperPlane,
  faPencil,
  faPenToSquare,
  faPeopleGroup,
  faPhone,
  faPlus,
  faPlusCircle,
  faQuestion,
  faQuestionCircle,
  faRightFromBracket,
  faSave,
  faScrewdriverWrench,
  faShare,
  faSpinner,
  faSquarePollVertical,
  faStar,
  faTag,
  faTachometerAlt,
  faTimes,
  faTimesCircle,
  faTrash,
  faTrophy,
  faUpload,
  faUser,
  faUserCheck,
  faUserCircle,
  faUserGear,
  faUserGroup,
  faUserPen,
  faUserPlus,
  faUsers,
  faUsersGear,
  faUserSecret,
  faUserSlash,
  faUserXmark,
  faVenus,
  faVenusMars,
  faXmark,
} from "@fortawesome/pro-solid-svg-icons";
import {faApple, faDiscord, faGoogle, faWaze} from "@fortawesome/free-brands-svg-icons";
import {faFile} from "@fortawesome/pro-regular-svg-icons";

import Chart from 'chart.js/auto';
import annotationPlugin from "chartjs-plugin-annotation";
import ChartDataLabels from 'chartjs-plugin-datalabels';

Chart.register(annotationPlugin, ChartDataLabels);

library.add(
    faAddressCard,
    faAngleLeft,
    faAngleRight,
    faApple,
    faArrowLeft,
    faArrowRight,
    faArrowRightFromBracket,
    faArrowsAlt,
    faArrowUpRightFromSquare,
    faArrowsRotate,
    faBan,
    faBell,
    faBolt,
    faBowArrow,
    faBox,
    faBoxes,
    faBuilding,
    faBullhorn,
    faBullseye,
    faCalendar,
    faCalendarCheck,
    faCalendarDays,
    faCalendarPlus,
    faCalendarWeek,
    faCalendarXmark,
    faChartBar,
    faChartLine,
    faCheck,
    faCheckCircle,
    faChevronLeft,
    faChevronRight,
    faCircleArrowRight,
    faCircleInfo,
    faCircleRight,
    faClock,
    faClipboardCheck,
    faClipboardList,
    faClockRotateLeft,
    faCog,
    faCogs,
    faComment,
    faCrosshairs,
    faDiscord,
    faDoorClosed,
    faDoorOpen,
    faDownload,
    faDumbbell,
    faEdit,
    faEllipsis,
    faEllipsisVertical,
    faEnvelope,
    faExclamationTriangle,
    faExternalLinkAlt,
    faEye,
    faFile,
    faFileContract,
    faFloppyDisk,
    faGaugeHigh,
    faGenderless,
    faGoogle,
    faHandHolding,
    faHeart,
    faHistory,
    faHome,
    faHourglass,
    faHourglassHalf,
    faIdBadge,
    faIdCard,
    faInfo,
    faInfoCircle,
    faInbox,
    faKey,
    faLightbulb,
    faList,
    faListCheck,
    faLock,
    faMap,
    faMapMarkerAlt,
    faMars,
    faMinus,
    faNoteSticky,
    faPaperclip,
    faPaperPlane,
    faPencil,
    faPenToSquare,
    faPeopleGroup,
    faPhone,
    faPlus,
    faPlusCircle,
    faQuestion,
    faQuestionCircle,
    faRightFromBracket,
    faSave,
    faScrewdriverWrench,
    faShare,
    faSpinner,
    faSquarePollVertical,
    faStar,
    faTag,
    faTachometerAlt,
    faTimes,
    faTimesCircle,
    faTrash,
    faTrophy,
    faUpload,
    faUser,
    faUserCheck,
    faUserCircle,
    faUserGear,
    faUserGroup,
    faUserPen,
    faUserPlus,
    faUserSecret,
    faUserSlash,
    faUsers,
    faUsersGear,
    faUserXmark,
    faVenus,
    faVenusMars,
    faXmark,
    faWaze
);

// Initialize Font Awesome after DOM is ready
document.addEventListener('DOMContentLoaded', () => {
    dom.watch();
});

// Initialize Bootstrap components after DOM is ready
document.addEventListener('DOMContentLoaded', () => {
    const tooltipTriggerList = Array.prototype.slice.call(document.querySelectorAll(
        '[data-bs-toggle="tooltip"]'
    ));
    tooltipTriggerList.forEach(
        (tooltipTriggerEl) => new bootstrap.Tooltip(tooltipTriggerEl)
    );

    const collections = [...document.querySelectorAll('.collection')];
    //formCollection(collections);
});
