import { Controller } from '@hotwired/stimulus';

/**
 * Shows/hides equipment-specific form field groups depending on which
 * equipment type is selected in the `club_equipment[type]` select field.
 *
 * Currently supported types and their field groups:
 *   - `bow`    → shows `#bow-fields`,   hides `#arrow-fields`
 *   - `arrows` → shows `#arrow-fields`, hides `#bow-fields`
 *   - anything else → hides both
 *
 * This controller attaches directly to the wrapping `<form>` element and
 * queries child elements by name/id rather than Stimulus targets, because
 * the fields are generated by Symfony's form builder and the selectors are
 * therefore stable.
 *
 * Usage:
 *   <form data-controller="equipment-type-toggle">…</form>
 */
export default class EquipmentTypeToggleController extends Controller {
    connect(): void {
        this.typeField?.addEventListener('change', this.update);
        this.update();
    }

    disconnect(): void {
        this.typeField?.removeEventListener('change', this.update);
    }

    readonly update = (): void => {
        const selectedType = this.typeField?.value;
        this.bowFields?.classList.toggle('d-none', selectedType !== 'bow');
        this.arrowFields?.classList.toggle('d-none', selectedType !== 'arrows');
    };

    private get typeField(): HTMLSelectElement | null {
        return this.element.querySelector('[name="club_equipment[type]"]');
    }

    private get bowFields(): HTMLElement | null {
        return this.element.querySelector('#bow-fields');
    }

    private get arrowFields(): HTMLElement | null {
        return this.element.querySelector('#arrow-fields');
    }
}
