import { Controller } from '@hotwired/stimulus';

/**
 * Toggles between the "existing user" and "new user" field groups on the
 * licensee-management step-4 form.
 *
 * When the "existing" radio button is selected, `#existing_user_field` is
 * shown and `#new_user_field` is hidden (and vice-versa). The visibility is
 * kept in sync both on initial connect and on every subsequent change.
 *
 * This controller queries its child elements by ID/value rather than Stimulus
 * targets because the DOM structure is generated by Symfony's form builder
 * and the selectors are stable.
 *
 * Usage:
 *   <div data-controller="user-choice"
 *        data-action="change->user-choice#update">
 *     <input type="radio" value="existing"> Compte existant
 *     <input type="radio" value="new">      Nouveau compte
 *     <div id="existing_user_field">…</div>
 *     <div id="new_user_field">…</div>
 *   </div>
 */
export default class UserChoiceController extends Controller {
    connect(): void {
        this.update();
    }

    update(): void {
        const shouldShowExisting = this.existingRadio?.checked ?? false;
        this.existingField?.classList.toggle('d-none', !shouldShowExisting);
        this.newField?.classList.toggle('d-none', shouldShowExisting);
    }

    private get existingRadio(): HTMLInputElement | null {
        return this.element.querySelector('input[value="existing"]');
    }

    private get existingField(): HTMLElement | null {
        return this.element.querySelector('#existing_user_field');
    }

    private get newField(): HTMLElement | null {
        return this.element.querySelector('#new_user_field');
    }
}
