name: PHP Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.php'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - # v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup PHP with PECL extension
        # 2.37.0
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f
        with:
          php-version: '8.4'
          extensions: ctype, gd, iconv, mbstring
      - name: Install
        run: composer install --prefer-dist
      - name: Run php-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix --config .php-cs-fixer.dist.php --dry-run --allow-risky=yes
        env:
          PHP_CS_FIXER_IGNORE_ENV: True

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - # v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup PHP with PECL extension
        # 2.37.0
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f
        with:
          php-version: '8.4'
          extensions: ctype, gd, iconv, mbstring
      - name: Install
        run: composer install --prefer-dist
      - name: Run phpstan
        run: ./vendor/bin/phpstan analyze

  rector:
    runs-on: ubuntu-latest
    steps:
      - # v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Setup PHP with PECL extension
        # 2.37.0
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f
        with:
          php-version: '8.4'
          extensions: ctype, gd, iconv, mbstring
      - name: Install
        run: composer install --prefer-dist
      - name: Run Rector
        run: ./vendor/bin/rector process --dry-run