name: PHP Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.php'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: ctype, gd, iconv, mbstring
      - name: Install
        run: composer install --prefer-dist
      - name: Run php-cs-fixer
        run: ./vendor/bin/php-cs-fixer fix --config .php-cs-fixer.dist.php --dry-run --allow-risky=yes
        env:
          PHP_CS_FIXER_IGNORE_ENV: True

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: ctype, gd, iconv, mbstring
      - name: Install
        run: composer install --prefer-dist
      - name: Run phpstan
        run: ./vendor/bin/phpstan analyze

  rector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: ctype, gd, iconv, mbstring
      - name: Install
        run: composer install --prefer-dist
      - name: Run Rector
        run: ./vendor/bin/rector process --dry-run