name: PHPStan

on:
  push:
    branches:
      - 'master'
  pull_request:
    paths:
      - '**.php'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install
        run: composer install

      - name: Run phpstan
        run: ./vendor/bin/phpstan analyze --level 2 src/ tests/